#!/bin/bash

set -e

if [ -n "$1" ]; then
    PORT="$1"
else
    PORT=9182
fi

docker build -t sonos-youtube:latest .
docker rm sonos-youtube-old || true
docker rename sonos-youtube sonos-youtube-old || true
docker stop sonos-youtube-old || true

docker run -d --restart=unless-stopped --name sonos-youtube -p $PORT:9182 \
    -e ENV=prod \
    -e LOGGING_LEVEL \
    sonos-youtube:latest
